[Log]
Environment = "development" # "production" or "development"
Level = "debug"
Outputs = ["stdout", "stderr"]

[State]
	[State.DB]
		Port = "5432"
		EnableLog = false
		MaxConns = 200
		[State.Batch]
			[State.Batch.Constraints]
			MaxTxsPerBatch = 300
			MaxBatchBytesSize = 120000
			MaxCumulativeGasUsed = 1125899906842624
			MaxKeccakHashes = 2145
			MaxPoseidonHashes = 252357
			MaxPoseidonPaddings = 135191
			MaxMemAligns = 236585
			MaxArithmetics = 236585
			MaxBinaries = 473170
			MaxSteps = 7570538
			MaxSHA256Hashes = 1596

[Pool]
FreeClaimGasLimit = 1500000
IntervalToRefreshBlockedAddresses = "5m"
IntervalToRefreshGasPrices = "5s"
MaxTxBytesSize=100132
MaxTxDataBytesSize=100000
DefaultMinGasPriceAllowed = 0
MinAllowedGasPriceInterval = "5m"
PollMinAllowedGasPriceInterval = "15s"
AccountQueue = 64
GlobalQueue = 1024
	[Pool.EffectiveGasPrice]
		Enabled = false
		L1GasPriceFactor = 0.25
		ByteGasCost = 16
		ZeroByteGasCost = 4
		NetProfit = 1
	    BreakEvenFactor = 1.1
		FinalDeviationPct = 10
		EthTransferGasPrice = 0
		EthTransferL1GasPriceFactor = 0
		L2GasPriceSuggesterFactor = 0.5
	[Pool.DB]
	Port = "5432"
	EnableLog = false
	MaxConns = 200

[Etherman]
ForkIDChunkSize = 20000
MultiGasProvider = false

[RPC]
Host = "0.0.0.0"
Port = 8123
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 5000
SequencerNodeURI = ""
EnableL2SuggestedGasPricePolling = true
	[RPC.WebSockets]
		Enabled = true
		Port = 8133

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100
SyncBlockProtection = "latest" # latest, finalized, safe
L1SynchronizationMode = "sequential"
	[Synchronizer.L1ParallelSynchronization]
		MaxClients = 10
		MaxPendingNoProcessedBlocks = 25
		RequestLastBlockPeriod = "5s"
		RequestLastBlockTimeout = "5s"
		RequestLastBlockMaxRetries = 3
		StatisticsPeriod = "5m"
		TimeoutMainLoop = "5m"
		RollupInfoRetriesSpacing= "5s"
		FallbackToSequentialModeOnSynchronized = false
		[Synchronizer.L1ParallelSynchronization.PerformanceWarning]
			AceptableInacctivityTime = "5s"
			ApplyAfterNumRollupReceived = 10

[L2GasPriceSuggester]
Type = "default"
UpdatePeriod = "10s"
Factor = 0.5
DefaultGasPriceWei = 0
MaxGasPriceWei = 0

[Executor]
MaxGRPCMessageSize = 100000000

[Metrics]
Host = "0.0.0.0"
Port = 9091
Enabled = true
ProfilingHost = "0.0.0.0"
ProfilingPort = 6060
ProfilingEnabled = true