networks:
  default:
    name: silicon

services:
  silicon-node:
    container_name: silicon-node
    image: 0xpolygon/cdk-validium-node:0.6.4-cdk.6
    restart: unless-stopped
    ports:
      - 8545:8545
      - 8546:8546
    environment:
      - ZKEVM_NODE_ISTRUSTEDSEQUENCER=false
      - ZKEVM_NODE_STATE_DB_USER=dbuser
      - ZKEVM_NODE_STATE_DB_PASSWORD=dbpassword
      - ZKEVM_NODE_STATE_DB_NAME=statedb
      - ZKEVM_NODE_STATE_DB_HOST=dbhost
      - ZKEVM_NODE_POOL_DB_USER=dbuser
      - ZKEVM_NODE_POOL_DB_PASSWORD=dbpassword
      - ZKEVM_NODE_POOL_DB_NAME=pooldb
      - ZKEVM_NODE_POOL_DB_HOST=dbhost
      - ZKEVM_NODE_MTCLIENT_URI=mtclienturi
      - ZKEVM_NODE_EXECUTOR_URI=executoruri
      - ZKEVM_NODE_ETHERMAN_URL=ethermanurl
      - ZKEVM_NODE_ETHERMAN_ETHERSCAN_APIKEY=etherscanapikey
    volumes:
      - ./node.toml:/app/config.toml
      - ./genesis.json:/app/genesis.json
    logging:
      driver: "json-file"
      options:
        max-size: 500m
        max-file: "3"
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components rpc"